/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface components {
  schemas: {
    ParamsFieldSchemaDto: {
      /** @enum {string} */
      type: 'date' | 'select' | 'number' | 'file';
      label: string;
      required: boolean;
      default?: number;
    };
    ReportTemplateDto: {
      id: string;
      type: string;
      name: string;
      description?: string | null;
      paramsSchema: {
        [key: string]: components['schemas']['ParamsFieldSchemaDto'];
      };
      sourceConfig: {
        [key: string]: unknown;
      };
      createdAt: string;
    };
    CreateTemplateDto: {
      name: string;
      description?: string | null;
      sourceConfig: {
        [key: string]: unknown;
      };
    };
    TemplateSourceDto: {
      id: string;
      label: string;
      /** @enum {string} */
      engine: 'clickhouse' | 'postgres';
      description?: string;
      defaultQuery?: string;
      dateField?: string;
    };
    RunReportDto: {
      /** @description Report run parameters (dateFrom, dateTo, etc.) */
      params: Record<string, never>;
    };
    ReportRunDto: {
      id: string;
      templateId: string;
      /** @enum {string} */
      status: 'pending' | 'running' | 'completed' | 'failed';
      resultPath?: string;
      error?: string;
      startedAt?: string;
      completedAt?: string;
      createdAt: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
